name: imagecaption
channels:
  - defaults
dependencies:
  - python=3.7
  - pip=19.0.3
  - numpy
  - pandas
  - pip:
    - flask==2.1.0
    - gunicorn==20.0.4
    - tensorflow==2.3.0
    - matplotlib==3.2.2
    - json5==0.9.5
    - pillow==7.2.0
    - transformers==2.11.0
    - grammarbot==0.2.0
    - nltk
    - textblob==0.15.3
    - regex>=2020.7.14
    - sklearn
